//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLPropyski.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ZayavkaClient = new HashSet<ZayavkaClient>();
        }
    
        public int id { get; set; }
        public string FName { get; set; }
        public string Name { get; set; }
        public string LName { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string NameOrganizatciya { get; set; }
        public string Primechanie { get; set; }
        public Nullable<System.DateTime> DateBirthfay { get; set; }
        public Nullable<decimal> PassportSeries { get; set; }
        public Nullable<decimal> PassportNumber { get; set; }
        public byte[] Images { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZayavkaClient> ZayavkaClient { get; set; }
    }
}
