//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLPropyski.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ZayavkaClient = new HashSet<ZayavkaClient>();
        }
    
        public int id { get; set; }
        public string FName { get; set; }
        public string Name { get; set; }
        public string LName { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string NameOrganizatciya { get; set; }
        public string Primechanie { get; set; }
        public Nullable<System.DateTime> DateBirthfay { get; set; }
        public Nullable<decimal> PassportSeries { get; set; }
        public Nullable<decimal> PassportNumber { get; set; }
        public byte[] Images { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZayavkaClient> ZayavkaClient { get; set; }
    }
}
