//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLPropyski.DBConnect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZayavkaEntities : DbContext
    {
        public ZayavkaEntities()
            : base("name=ZayavkaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlackList> BlackList { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Podrazdel> Podrazdel { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TypeZayavka> TypeZayavka { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<VisitPurpose> VisitPurpose { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
        public virtual DbSet<ZayavkaClient> ZayavkaClient { get; set; }
    }
}
