//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLPropyski.DBConnect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zayavka2Entities : DbContext
    {
        public Zayavka2Entities()
            : base("name=Zayavka2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlackList> BlackList { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Podrazdel> Podrazdel { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TypeZayavka> TypeZayavka { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<VisitPurpose> VisitPurpose { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
        public virtual DbSet<ZayavkaClient> ZayavkaClient { get; set; }
    }
}
