//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLPropyski.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZayavkaClient
    {
        public int id { get; set; }
        public Nullable<int> ZayavkaID { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Zayavka Zayavka { get; set; }
    }
}
