//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLPropyski.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zayavka()
        {
            this.ZayavkaClient = new HashSet<ZayavkaClient>();
        }
    
        public int id { get; set; }
        public Nullable<int> TypeZayavkaID { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateStop { get; set; }
        public Nullable<int> VisitID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string ResultBecouse { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PodrazdelEmplID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeZayavka TypeZayavka { get; set; }
        public virtual User User { get; set; }
        public virtual VisitPurpose VisitPurpose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZayavkaClient> ZayavkaClient { get; set; }
    }
}
