//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLPropyski.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZayavkaClient
    {
        public int id { get; set; }
        public Nullable<int> ZayavkaID { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Zayavka Zayavka { get; set; }
    }
}
